declare const _default: {
    primary: string;
    success: string;
    info: string;
    warning: string;
    error: string;
    default: string;
    fontSizeH1: string;
    fontSizeH2: string;
    fontSizeH3: string;
    fontSizeH4: string;
    fontSizeH5: string;
    fontColor: string;
    fontColor2: string;
    fontColor3: string;
    pMargin: string;
    hoverTheme: string;
    radiusMini: string;
};
export default _default;
